# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-15 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0009_auto_20160515_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='confirmed_party_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
