# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-04 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0010_auto_20160515_2202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rsvp',
            options={'verbose_name': 'RSVP', 'verbose_name_plural': 'RSVPs'},
        ),
        migrations.AddField(
            model_name='rsvp',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
